### ISSUE TITLE
Do not receive messages in Slack

### ISSUE THREAD

**Issue by Artein** [wlisac/swift-log-slack#2] opened 2021-09-12 09:12 UTC
Hi, @wlisac !

Setup everything according to Usage section of the repo main page.
Everything compile and my iOS app launches with no errors.
I even see my logs in Console, but not receive messages in Slack.

Additionally checked webhook url with curl - message was received successfully.

@wlisac, could you help me?

**Comment by xpnewmedia** [comment] 2021-11-03 22:49
I've recently tried this library as well. And didn't find any message in slack.

**Comment by xpnewmedia** [comment] 2021-11-03 23:03
Maybe this will help us:


```
Log Level Threshold

Only critical log level messages are sent to Slack by default.

You can adjust the log level threshold by changing the globalLogLevelThreshold static property on SlackLogHandler.

For example, this will configure LoggingSlack to send all error log level and above messages to Slack.
```
Set: .info, .debug, .error as needed
```
SlackLogHandler.globalLogLevelThreshold = .error 
```

That was the issue for me.
The Library is now working as intended.

**Comment by wlisac** [comment] 2021-12-05 21:19
It sounds like adjusting `SlackLogHandler.globalLogLevelThreshold` will resolve the issue. Closing – feel free t reopen if that doesn't work.

**Closed as completed by wlisac** 2021-12-05 21:19 UTC
